from tkinter import *
root=Tk()
var1=IntVar()
var2=IntVar()
check1=Checkbutton(root,text=u'1 пункт  ',variable=var1,onvalue=1,offvalue=0)
check2=Checkbutton(root,text=u'2 пункт',variable=var2,onvalue=1,offvalue=0)
check3=Checkbutton(root,text=u'3 пункт',variable=var1,onvalue=1,offvalue=0)
check4=Checkbutton(root,text=u'4 пункт',variable=var2,onvalue=1,offvalue=0)
check5=Checkbutton(root,text=u'5 пункт',variable=var1,onvalue=1,offvalue=0)
check6=Checkbutton(root,text=u'6 пункт',variable=var2,onvalue=1,offvalue=0)
check1.pack()
check2.pack()
check3.pack()
check4.pack()
check5.pack()
check6.pack()
root.mainloop()